### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by seoprodaddy** [trevorhobenshield/twitter-api-client#168]
I am new to python. It seems the OP doesn't want to support proxies. For scraping twitter, proxies are a must else people will lose access to their bots.

Please can someone help me with sample code on how to subclass Account, Scraper, Search so it can use proxies?

I looked the code but it is way too advanced me to grasp what is going on or know where to include it.

Thanks for your help in advance.

**Comment by david-lev** [comment]
Hi, `Account` seems to accept [httpx Client](https://www.python-httpx.org/api/#client) for its session parameter.
So you can do something like:

```python
import httpx
from twitter.account import Account

account = Account(..., session=httpx.Client(..., proxy='https://proxy.com')). # or proxies={...}
```

By the way, this seems relevant only to the cookies method, because when logging in with a user and password, the impl ignores the provided session:
https://github.com/trevorhobenshield/twitter-api-client/blob/main/twitter/account.py#L621
https://github.com/trevorhobenshield/twitter-api-client/blob/main/twitter/login.py#L150
