### ISSUE TITLE
Is email required?

### ISSUE THREAD

**Issue by Kamigaku** [trevorhobenshield/twitter-api-client#34]
Hey,

For of all, thanks for the library, it's working perfectly.
I have one question, recently you've added the "email" parameter to the Scraper and it's also one of the parameter in the Account class.
Is it required if I have a username parameter setted when building either of those?

When logging to twitter from webpage, you can either use an email or a username to connect.
If I don't specify one, some features won't work?

Thanks!

**Comment by trevorhobenshield** [comment]
Yes email, username, and password are all required now. I added the extra email parameter to make the login verification process more automated. The reason is because Twitter often issues irregular email verification challenges for new accounts, so instead of prompting you to input your email (which you may not remember) every time an email challenge is issued, I made it a requirement to include your email.
