### ISSUE TITLE
api key or account ban risk?

### ISSUE THREAD

**Issue by dustingetz** [trevorhobenshield/twitter-api-client#4]
Hey thanks for this library, do you know what the risk profile is for this?

**Comment by trevorhobenshield** [comment]
The account automation module is all synchronous, so there is little risk of flagging suspicious activity as long as API quotas aren't hit too frequently. So far none of my test accounts have been banned since I created this ~2 weeks ago.

The scraping and search modules are async and have the potential to pull a few GB of data in under a minute. I've had about 3/10 test accounts banned due to these high volumes of async requests, which is understandable. For these operations it is important to use test accounts and spread requests across multiple accounts and IPs.
