### ISSUE TITLE
How does reply_to=123 work?

### ISSUE THREAD

**Issue by CryptoKingCro** [trevorhobenshield/twitter-api-client#5]
It appears that i don't really understand how the reply_to parameter for a tweet can be used.

I used it like:

account.tweet(msg,reply_to = ele[0])

Where msg is a string and ele[o] is the id if the tweet i want to answer. 
The msg string is beginning with an @name.

What am i doing wrong?

Edit: stunning work btw.

**Comment by AaronEichler** [comment]
I just saw in your code that reply to is only available for sceduled tweets, right? 

As you know your code muuuuch better, would a change here be possible?

I don't want to be demanding and would use a workaround if you don't want/can change this atm..

Regards :)

**Comment by trevorhobenshield** [comment]
I think someone else also had a similar issue. I'm going to be removing those keyword arguments for `tweet()` in the future to avoid confusion. I may also refactor these methods to make the API slightly more intuitive.

Basically, `tweet()` is only intended to accept a message and an optional media parameter. Kwargs **aren't supposed to be used directly**, only the methods `reply()`, `quote()`, and `create_poll()` are supposed to be using them. This is because all of these methods are calling the same endpoint that `tweet()` does, but with some extra parameters

On the other hand `retweet()` and `schedule_tweet()` use entirely different endpoints, so they cannot simply call `tweet()` with extra params.

To answer your specific questions:

> I just saw in your code that reply to is only available for sceduled tweets, right?

Nope, we can reply to a tweet simply using `reply()`. Scheduled tweets use a different endpoint, so I've currently created a seperate method for them as you may have seen in the readme.

> What am i doing wrong?

If you only care about replying to a tweet you can simply use the method `reply()`
```python
account.reply(123, 'my reply')
```

If you want to schedule a reply, a different method is used:
```python
account.schedule_tweet('my scheduled reply', '2023-04-20 19:11', reply_to=123456)

## or with a unix timestamp
# account.schedule_tweet('my scheduled reply', 1682043060, reply_to=123456)
```

**Comment by AaronEichler** [comment]
i was dumb enough to not see the reply function...

Thanks a lot for clarification!
