### ISSUE TITLE
Account functions not working

### ISSUE THREAD

**Issue by trevtravtrev** [trevorhobenshield/twitter-api-client#9]
I've now tested every function in every module (account, scraper, search) using multiple accounts, and multiple vpns/no vpn. None of the codebase works for me. Any ideas?
code:
```
from twitter.account import Account
    account = Account('myuser', 'mypass')
    account.tweet('hello')
```

error:
```
[SUCCESS] myuser logged in successfully
2023-04-08 17:08:53,204.204 DEBUG: FAILED to combine search results, input length is 0: line 1 column 1 (char 0)
```

**Comment by trevorhobenshield** [comment]
All functions are still working, however Twitter has added another Arkose challenge after successful login. I've also been meaning to add some more helpful error messages and clean up the login flow (the successful login message is currently misleading, it still shows even when email or Arkose challenges are pending)

Almost all errors will be caused by security/anti-bot measures being enforced, such as an Arkose challenge, email verification, etc. The solution is to log in to the account normally in the browser and complete the challenges, switch to a different VPN, then log in again on the new VPN and ensure there are no pending challenges. You may need to try many different VPNs (sometimes all US ones get blocked) or residential ones.
